name: Build and Release Tauri App

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions
  release:
    types: [published]  # Triggers the workflow when a release is published

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]  # Choose the Node.js version you need
        tauri-target: [x86_64-unknown-linux-gnu]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Rust and Tauri dependencies
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.0-dev libgtk-3-dev curl wget
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          rustup target add ${{ matrix.tauri-target }}

      - name: Install NPM dependencies
        run: npm install

      - name: Install Tauri CLI
        run: cargo install tauri-cli

      - name: Build Tauri app
        run: npm run tauri build

      - name: Upload the Tauri Linux artifact
        uses: actions/upload-artifact@v3
        with:
          name: tauri-linux-app
          path: src-tauri/target/release/bundle

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}  # Release name
          artifacts: |
            src-tauri/target/release/bundle/**/*.AppImage
            src-tauri/target/release/bundle/**/*.deb
            src-tauri/target/release/bundle/**/*.rpm
          token: ${{ secrets.GITHUB_TOKEN }}
